// SViewCharacter.cpp


#include "Characters/SViewCharacter.h"
#include "Components/CapsuleComponent.h"
#include "GameFramework/SpringArmComponent.h"
#include "Camera/CameraComponent.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "Components/InputComponent.h"
#include "GameFramework/Controller.h"
#include "EnhancedInputComponent.h"
#include "EnhancedInputSubsystems.h"
#include "Inputs/SInputConfigData.h"

ASViewCharacter::ASViewCharacter()
{
    PrimaryActorTick.bCanEverTick = true;

}

void ASViewCharacter::BeginPlay()
{
    Super::BeginPlay();

    APlayerController* PlayerController = Cast<APlayerController>(GetController());
    if (true == ::IsValid(PlayerController))
    {
        UEnhancedInputLocalPlayerSubsystem* Subsystem = ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(PlayerController->GetLocalPlayer());
        if (true == ::IsValid(Subsystem))
        {
            Subsystem->AddMappingContext(PlayerCharacterInputMappingContext, 0);
        }
    }
}

void ASViewCharacter::PossessedBy(AController* NewController)
{
    Super::PossessedBy(NewController);

    //SetViewMode(EViewMode::QuarterView);
    SetViewMode(EViewMode::BackView);
    DestArmLength = 400.f; // 초기화에서 한 번 지정해줘야 함.
    DestArmRotation = FRotator::ZeroRotator;
}

void ASViewCharacter::Tick(float DeltaSeconds)
{
    Super::Tick(DeltaSeconds);

    switch (CurrentViewMode)
    {
        case EViewMode::BackView:
            break;

        case EViewMode::QuarterView:
        {
            if (KINDA_SMALL_NUMBER < DirectionToMove.SizeSquared())
            {
                GetController()->SetControlRotation(FRotationMatrix::MakeFromX(DirectionToMove).Rotator());
                AddMovementInput(DirectionToMove);
                DirectionToMove = FVector::ZeroVector;
            }
            break;
        }

        case EViewMode::End:
            break;

        default:
            break;
    }

    if (KINDA_SMALL_NUMBER < abs(DestArmLength - SpringArmComponent->TargetArmLength))
    {
        SpringArmComponent->TargetArmLength = FMath::FInterpTo(SpringArmComponent->TargetArmLength, DestArmLength, DeltaSeconds, ArmLengthChangeSpeed);
        SpringArmComponent->SetRelativeRotation(FMath::RInterpTo(SpringArmComponent->GetRelativeRotation(), DestArmRotation, DeltaSeconds, ArmRotationChangeSpeed));
    }
}

void ASViewCharacter::ChangeView(const FInputActionValue& InValue)
{
    switch (CurrentViewMode)
    {
        case EViewMode::BackView:
            /* Case 1. 이전에 BackView 시점이었다면

              BackView는 컨트롤 회전값 == 스프링암 회전값.
              그러나 QuarterView는 캐릭터의 회전값 == 컨트롤 회전값.
              따라서 시점 변경 전에 캐릭터의 현재 회전값을 컨트롤 회전에 세팅해둬야 함.
              안그러면 컨트롤 회전이 일어나면서 현재 캐릭터의 회전값이 스프링암 회전값(컨트롤 회전값)으로 동기화됨.
            */
            GetController()->SetControlRotation(GetActorRotation());
            DestArmLength = 900.f;
            DestArmRotation = FRotator(-45.f, 0.f, 0.f);
            SetViewMode(EViewMode::QuarterView);

            break;

        case EViewMode::QuarterView:
            /* Case 2. 이전에 QuarterView 시점이었다면

              컨트롤 회전이 캐릭터 회전에 맞춰져 있을거임.
              //QuarterView는 현재 스프링암의 회전값을 컨트롤 회전에 세팅해둔 상태에서 시점 변경해야 올바름.
              BackView에서는 컨트롤 로테이션이 폰의 회전과 동기화되고 폰의 회전이 스프링 암의 회전과 동기화.
              따라서 스프링 암의 회전을 임의로 설정할 수 없음. 0으로 고정.
            */
            // 만약 현재 액터의 방향으로 BackView를 전환하고 싶다면,
            // FRotator::ZeroRotator 대신 GetActorRotation()를 사용

            GetController()->SetControlRotation(FRotator::ZeroRotator);
            DestArmLength = 400.f;
            DestArmRotation = FRotator::ZeroRotator;
            SetViewMode(EViewMode::BackView);

            break;

        case EViewMode::End:
            break;

        default:
            break;
    }
}

void ASViewCharacter::SetViewMode(EViewMode InViewMode)
{
    if (CurrentViewMode == InViewMode)
    {
        return;
    }

    CurrentViewMode = InViewMode;

    switch (CurrentViewMode)
    {
        case EViewMode::BackView:
            //SpringArmComponent->TargetArmLength = 400.f;
            //SpringArmComponent->SetRelativeRotation(FRotator::ZeroRotator);
            //// ControlRotation이 Pawn의 회전과 동기화 -> Pawn의 회전이 SprintArm의 회전 동기화. 이로 인해 SetRotation()이 무의미.

            bUseControllerRotationPitch = false;
            bUseControllerRotationYaw = false;
            bUseControllerRotationRoll = false;

            SpringArmComponent->bUsePawnControlRotation = true;
            SpringArmComponent->bDoCollisionTest = true;
            SpringArmComponent->bInheritPitch = true;
            SpringArmComponent->bInheritYaw = true;
            SpringArmComponent->bInheritRoll = false;

            GetCharacterMovement()->bOrientRotationToMovement = true;
            GetCharacterMovement()->bUseControllerDesiredRotation = false;
            GetCharacterMovement()->RotationRate = FRotator(0.f, 480.f, 0.f);

            break;

        case EViewMode::QuarterView:
            //SpringArmComponent->TargetArmLength = 900.f;
            //SpringArmComponent->SetRelativeRotation(FRotator(-45.f, 0.f, 0.f));

            bUseControllerRotationPitch = false;
            bUseControllerRotationYaw = false;
            bUseControllerRotationRoll = false;

            SpringArmComponent->bUsePawnControlRotation = false;
            SpringArmComponent->bDoCollisionTest = false;
            SpringArmComponent->bInheritPitch = false;
            SpringArmComponent->bInheritYaw = false;
            SpringArmComponent->bInheritRoll = false;

            GetCharacterMovement()->bOrientRotationToMovement = false;// 이동키 누르면 동기화
            GetCharacterMovement()->bUseControllerDesiredRotation = true;// bUseControllerRotationYaw와의 차이점은 컨트롤 로테이션에 딜레이를 주는 것
            GetCharacterMovement()->RotationRate = FRotator(0.f, 480.f, 0.f);

            break;

        case EViewMode::End:
            break;
    
        default:
            break;
    }
}

void ASViewCharacter::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
    Super::SetupPlayerInputComponent(PlayerInputComponent);

    UEnhancedInputComponent* EnhancedInputComponent = Cast<UEnhancedInputComponent>(PlayerInputComponent);
    if (true == ::IsValid(EnhancedInputComponent))
    {
        EnhancedInputComponent->BindAction(PlayerCharacterInputConfigData->MoveAction, ETriggerEvent::Triggered, this, &ASViewCharacter::Move);
        EnhancedInputComponent->BindAction(PlayerCharacterInputConfigData->LookAction, ETriggerEvent::Triggered, this, &ASViewCharacter::Look);
        EnhancedInputComponent->BindAction(PlayerCharacterInputConfigData->ChangeViewAction, ETriggerEvent::Started, this, &ASViewCharacter::ChangeView);
    }
}

void ASViewCharacter::Move(const FInputActionValue& InValue)
{
    FVector2D MovementVector = InValue.Get<FVector2D>();

    switch (CurrentViewMode)
    {
        case EViewMode::None:
            break;

        case EViewMode::BackView:
        { // Switch-Case 구문 내에서 Scope를 지정하면 해당 Scope 내에서 변수 선언이 가능해짐.
            const FRotator ControlRotation = GetController()->GetControlRotation();
            const FRotator ControlRotationYaw(0.f, ControlRotation.Yaw, 0.f);

            const FVector ForwardVector = FRotationMatrix(ControlRotationYaw).GetUnitAxis(EAxis::X);
            const FVector RightVector = FRotationMatrix(ControlRotationYaw).GetUnitAxis(EAxis::Y);

            AddMovementInput(ForwardVector, MovementVector.X);
            AddMovementInput(RightVector, MovementVector.Y);

            break;
        }

        case EViewMode::QuarterView:
            DirectionToMove.X = MovementVector.X;
            DirectionToMove.Y = MovementVector.Y;

            break;

        case EViewMode::End:
            break;

        default:
            AddMovementInput(GetActorForwardVector(), MovementVector.X);
            AddMovementInput(GetActorRightVector(), MovementVector.Y);
            break;
    }
}

void ASViewCharacter::Look(const FInputActionValue& InValue)
{
    FVector2D LookVector = InValue.Get<FVector2D>();

    switch (CurrentViewMode)
    {
        case EViewMode::None:
            break;

        case EViewMode::BackView:
            AddControllerYawInput(LookVector.X);
            AddControllerPitchInput(LookVector.Y);
            break;

        case EViewMode::QuarterView:
            break;

        case EViewMode::End:
            break;

        default:
            break;
    }
}